// <auto-generated />
using AbstraCountries.Resources.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbstraCountries.Resources.Migrations
{
    [DbContext(typeof(AbstraCountriesDbContext))]
    partial class AbstraCountriesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbstraCountries.Resources.Data.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = "CI",
                            Name = "Côte d’Ivoire"
                        },
                        new
                        {
                            Id = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = "CG",
                            Name = "Congo - Brazzaville"
                        },
                        new
                        {
                            Id = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = "ZW",
                            Name = "Zimbabwe"
                        },
                        new
                        {
                            Id = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = "CD",
                            Name = "Congo - Kinshasa"
                        },
                        new
                        {
                            Id = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = "SZ",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = "ST",
                            Name = "São Tomé & Príncipe"
                        },
                        new
                        {
                            Id = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = "AG",
                            Name = "Antigua & Barbuda"
                        },
                        new
                        {
                            Id = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = "CW",
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = "TC",
                            Name = "Turks & Caicos Islands"
                        },
                        new
                        {
                            Id = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = "BQ",
                            Name = "Caribbean Netherlands"
                        },
                        new
                        {
                            Id = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = "SX",
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = "MF",
                            Name = "St. Martin"
                        },
                        new
                        {
                            Id = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = "PM",
                            Name = "St. Pierre & Miquelon"
                        },
                        new
                        {
                            Id = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = "TT",
                            Name = "Trinidad & Tobago"
                        },
                        new
                        {
                            Id = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = "BL",
                            Name = "St. Barthélemy"
                        },
                        new
                        {
                            Id = "KN",
                            Name = "St. Kitts & Nevis"
                        },
                        new
                        {
                            Id = "LC",
                            Name = "St. Lucia"
                        },
                        new
                        {
                            Id = "VI",
                            Name = "U.S. Virgin Islands"
                        },
                        new
                        {
                            Id = "VC",
                            Name = "St. Vincent & Grenadines"
                        },
                        new
                        {
                            Id = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = "VG",
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = "SJ",
                            Name = "Svalbard & Jan Mayen"
                        },
                        new
                        {
                            Id = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = "PS",
                            Name = "Palestinian Territories"
                        },
                        new
                        {
                            Id = "HK",
                            Name = "Hong Kong SAR China"
                        },
                        new
                        {
                            Id = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = "MO",
                            Name = "Macao SAR China"
                        },
                        new
                        {
                            Id = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = "KP",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = "KR",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = "GS",
                            Name = "South Georgia & South Sandwich Islands"
                        },
                        new
                        {
                            Id = "TA",
                            Name = "Tristan da Cunha"
                        },
                        new
                        {
                            Id = "FK",
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Id = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = "AX",
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = "CZ",
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = "BA",
                            Name = "Bosnia & Herzegovina"
                        },
                        new
                        {
                            Id = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = "MK",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = "VA",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = "DG",
                            Name = "Diego Garcia"
                        },
                        new
                        {
                            Id = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = "RE",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = "UM",
                            Name = "U.S. Outlying Islands"
                        },
                        new
                        {
                            Id = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = "PN",
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = "WF",
                            Name = "Wallis & Futuna"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
